# Generated by Django 5.0.6 on 2024-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_basic_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
