# Generated by Django 5.0.6 on 2024-05-31 23:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airport_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
