# Generated by Django 5.0.6 on 2024-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='terminal',
            field=models.CharField(default='T1', max_length=50),
        ),
    ]
