# Generated by Django 5.0.6 on 2024-06-05 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='frequent_flyer_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='special_needs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
