# Generated by Django 5.0.6 on 2024-06-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_passenger_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
